theme: minima
title: Irene's Thoughts
author: Irene Salazar Medina
description: With a background in Mechatronics Engineering, Irene has been plunged into the world of Human-Machine Understanding and Affective Computing. She has spent the past 2 years working to bring affective and cognitive models into machines so our computers can empathise with us in both reason and emotion. The intersection of cutting edge technology and human wellbeing is where she wants to be!